language: node_js
node_js:
  - "6"
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
before_install:
  - npm install
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: ""
after_success:
  # Send coverage data to coveralls.
  - npm run test:cover:travis