language: node_js
node_js:
  - "6"
before_script:
  - npm install
script:
  - npm run dist
deploy:
  provider: s3
  access_key_id: "$ACCESS_KEY_ID"
  secrete_access_key: "$SECRET_ACCESS_KEY"
  bucket: "reactredux.danielparker.com.au"
  skip_cleanup: true
  acl: public_read
  region: ap-southeast-2
  local_dir: dist
  on:
    branch: master
